=== BrioNetworks/mokai/mokai-core/src/main/resources/org/mokai/config/xml/connectors-0.8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified"
           targetNamespace="http://mokai.googlecode.com/connectors"
           xmlns:connectors="http://mokai.googlecode.com/connectors">

	<xs:element name="connectors">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="connectors:connector"/>
            </xs:choice>
       </xs:complexType>
	</xs:element> 
	
	<xs:element name="connector">
		<xs:complexType>
			<xs:all>
        		<xs:element ref="connectors:configuration" minOccurs="0"/>
        		<xs:element ref="connectors:acceptors" minOccurs="0" />
        		<xs:element ref="connectors:pre-processing-actions" minOccurs="0" />
        		<xs:element ref="connectors:post-processing-actions" minOccurs="0" />
        		<xs:element ref="connectors:post-receiving-actions" minOccurs="0" />
        	</xs:all>
        	
        	<xs:attribute name="id" type="xs:string" use="required"/>
        	<xs:attribute name="priority" type="xs:int" />
			<xs:attribute name="maxConcurrentMsgs" type="xs:int" />
        	<xs:attribute name="className" type="xs:string" use="required" />
        </xs:complexType>
	</xs:element>
	
	<xs:element name="configuration">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="connectors:property"/>
				<xs:element ref="connectors:mapProperty"/>
				<xs:element ref="connectors:listProperty"/>
			</xs:choice>
        </xs:complexType>
	</xs:element>
	
	<xs:element name="acceptors">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
        		<xs:element ref="connectors:acceptor" />
        		<xs:element name="and" type="connectors:andOrType" />
        		<xs:element name="or" type="connectors:andOrType" />
        	</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="acceptor" type="connectors:acceptorType" />
	
	<xs:element name="pre-processing-actions">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
        		<xs:element ref="connectors:action" />
        	</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="post-processing-actions">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
        		<xs:element ref="connectors:action" />
        	</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="post-receiving-actions">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
        		<xs:element ref="connectors:action" />
        	</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="action" type="connectors:extensionType" />
	
	<xs:complexType name="andOrType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="connectors:acceptor" />
			<xs:element name="and" type="connectors:andOrType" />
        	<xs:element name="or" type="connectors:andOrType" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="acceptorType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="connectors:property"/>
			<xs:element ref="connectors:mapProperty"/>
			<xs:element ref="connectors:listProperty"/>
			<xs:element name="and" type="connectors:andOrType" />
        	<xs:element name="or" type="connectors:andOrType" />
		</xs:choice>
		
		<xs:attribute name="className" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="extensionType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="connectors:property"/>
			<xs:element ref="connectors:mapProperty"/>
			<xs:element ref="connectors:listProperty"/>
		</xs:choice>
		
		<xs:attribute name="className" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:element name="property">
		<xs:complexType mixed="true">
			<xs:sequence>
          		<xs:element ref="connectors:acceptor" minOccurs="0" />
          		<xs:element name="connector" type="connectors:extensionType" minOccurs="0" />
        	</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="mapProperty">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="item">
					<xs:complexType mixed="true">
						<xs:sequence>
          					<xs:element ref="connectors:acceptor" minOccurs="0" />
          					<xs:element name="connector" type="connectors:extensionType" minOccurs="0" />
        				</xs:sequence>
						<xs:attribute name="key" type="xs:string" use="required" />
						<xs:attribute name="value" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
			
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="listProperty">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="item">
					<xs:complexType mixed="true">
						<xs:sequence>
          					<xs:element ref="connectors:acceptor" minOccurs="0" />
          					<xs:element name="connector" type="connectors:extensionType" minOccurs="0" />
        				</xs:sequence>
						<xs:attribute name="value" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
			
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
           
</xs:schema>

=== BrioNetworks/mokai/mokai-core/src/test/resources/config-test/nested-acceptors-connectors.xml
<?xml version="1.0" encoding="UTF-8"?>

<connectors xmlns="http://mokai.googlecode.com/connectors" 
		    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:schemaLocation=
		   		"http://mokai.googlecode.com/connectors http://mokai.googlecode.com/svn/schema/connectors-0.8.xsd">
		   		
	<connector id="test-1" priority="1" maxConcurrentMsgs="10" className="org.mokai.types.mock.MockConnector">
		<acceptors>
			<acceptor className="org.mokai.types.mock.MockAcceptorWithAcceptor">
				<property name="acceptor">
					<acceptor className="org.mokai.types.mock.MockAcceptor" />
				</property>
				<listProperty name="listAcceptors">
					<item><acceptor className="org.mokai.types.mock.MockAcceptor" /></item>
				</listProperty>
				<mapProperty name="mapAcceptors">
					<item key="test1"><acceptor className="org.mokai.types.mock.MockAcceptor" /></item>
				</mapProperty>
			</acceptor>
		</acceptors>
	</connector>
	
</connectors>

=== BrioNetworks/mokai/mokai-core/src/test/resources/config-test/nested-connectors-connectors.xml
<?xml version="1.0" encoding="UTF-8"?>

<connectors xmlns="http://mokai.googlecode.com/connectors" 
		    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:schemaLocation=
		   		"http://mokai.googlecode.com/connectors http://mokai.googlecode.com/svn/schema/connectors-0.8.xsd">
		   		
	<connector id="test-1" priority="1" maxConcurrentMsgs="10" className="org.mokai.types.mock.MockConnectorWithConnectors">
		<configuration>
			<property name="connector"><connector className="org.mokai.types.mock.MockConnector" /></property>
			<listProperty name="listConnectors">
				<item><connector className="org.mokai.types.mock.MockConnector" /></item>
			</listProperty>
			<mapProperty name="mapConnectors">
				<item key="test-1">
					<connector className="org.mokai.types.mock.MockConfigurableConnector">
						<property name="config1" value="config1" />
						<property name="config2" value="2" />
					</connector>
				</item>
			</mapProperty>
		</configuration>
	</connector>
	
</connectors>
