=== BrioNetworks/mokai/mokai-core/src/main/resources/org/mokai/config/xml/receivers-0.2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified"
           targetNamespace="http://mokai.googlecode.com/receivers"
           xmlns:receivers="http://mokai.googlecode.com/receivers">

	<xs:element name="receivers">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="receivers:receiver"/>
            </xs:choice>
       </xs:complexType>
	</xs:element>
	
	<xs:element name="receiver">
		<xs:complexType>
			<xs:all>
        		<xs:element ref="receivers:configuration" minOccurs="0"/>
        		<xs:element ref="receivers:post-receiving-actions" minOccurs="0" />
        	</xs:all>
        	
        	<xs:attribute name="id" type="xs:string" use="required"/>
        	<xs:attribute name="className" type="xs:string" use="required" />
        	<xs:attribute name="type" type="xs:string" />
        </xs:complexType>
	</xs:element>
	
	<xs:element name="post-receiving-actions">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
        		<xs:element ref="receivers:action" />
        	</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="action">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="receivers:property"/>
				<xs:element ref="receivers:mapProperty"/>
				<xs:element ref="receivers:listProperty"/>
			</xs:choice>
		
			<xs:attribute name="className" type="xs:string" />
			<xs:attribute name="type" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="configuration">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="receivers:property"/>
				<xs:element ref="receivers:mapProperty"/>
				<xs:element ref="receivers:listProperty"/>
			</xs:choice>
        </xs:complexType>
	</xs:element>
	
	<xs:element name="property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="value" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
			
		</xs:complexType>
	</xs:element>
	
	<xs:element name="mapProperty">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="item">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="key" type="xs:string" use="required" />
								<xs:attribute name="value" type="xs:string" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="listProperty">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="item">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="value" type="xs:string" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			</xs:choice>
			
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== BrioNetworks/mokai/mokai-core/src/test/resources/schema-test/good-receivers.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<receivers xmlns="http://mokai.googlecode.com/receivers" 
		   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:schemaLocation=
		   	"http://mokai.googlecode.com/receivers http://mokai.googlecode.com/svn/schema/receivers-0.2.xsd">

  <receiver id="test-1" className="org.mokai.types.mock.MockConnector" >
  	<post-receiving-actions>
  		<action className="org.mokai.types.mock.MockAction">
  		  <property name="test">test1á</property>
  		  <listProperty name="test2áñ">
  		  	<item>testí</item>
  		  	<item value="test2ñ" />
  		  </listProperty>
  		  <mapProperty name="teñst3">
  		  	<item key="testé">tóest</item>
  		  	<item key="test2" value="test2" />
  		  </mapProperty>
  		</action>
  	</post-receiving-actions>
  </receiver>
  
  <receiver id="test-2" className="org.mokai.types.mock.MockConfigurableConnector">
  	<configuration>
  	  <property name="test">test1</property>
  	  <listProperty name="test2">
  		<item>test</item>
  		<item value="test2" />
  	  </listProperty>
  	  <mapProperty name="test3">
  		<item key="test">test</item>
  		<item key="test2" value="test2" />
  	  </mapProperty>
  	</configuration>
  	<post-receiving-actions>
  	  <action className="org.mokai.types.mock.MockConfigurableAction">
  		<property name="config1">test</property>
  		<property name="config2">2</property>
  	  </action>
  	</post-receiving-actions>
  </receiver>
  	   	
</receivers>
